# -*- coding: utf-8 -*-
"""detect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nfPKPxH0TCs9AxPYXcsRRnGrD5LXOGkl
"""

import cv2
import tensorflow as tf

CATEGORIES = ["Not_Retinoblastoma", "Retinoblastoma"]

def prepare(filepath):
    IMG_SIZE = 1000
    img_array = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
    new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
    return new_array.reshape(-1, IMG_SIZE, IMG_SIZE, 1)

model = tf.keras.models.load_model("28-CNN1.model")

prediction = model.predict([prepare('6.jpg')])
print(CATEGORIES[int(prediction[0][0])])

